config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in:"login", sign_out:"logout"}

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  get 'users/:id',    to: 'users#show',    as: 'user'
  get 'users',    to: 'users#index',    as: 'users'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username, :email, :password, :password_confirmation]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def index
    @users = User.all
  end

  def show
    @user = User.find_by_username(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Интерактивные списки"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">© ListThis! 2016</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "Help",    help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" >
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "ListThis!", root_path, id: "logo" %>
          <nav>
            <ul class="nav navbar-right  navbar-nav">
              <% if user_signed_in? %>
              <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
              <li><%= link_to current_user.username, current_user %></li>
              <% else %>
              <li><%= link_to "Войти", new_user_session_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
    <div class="container">
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
    <h1>Help</h1>
    <p>
      Для получения помощи дождитесь когда все будет готово:)
    </p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
    <h1>ListThis!</h1>
    <h2>
      Это домашняя страница ListThis!
    </h2>
    </div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul >
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, :action =>'show', :id => user.id %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= @user.username %>
<% if user_signed_in? %>
<%= link_to 'Редактировать', edit_user_registration_path %>
<% end %>